kind: Service
apiVersion: v1
metadata:
  name: retal-loans-business-application-service
  labels:
    app: retal-loans-business-application-service
spec:
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: retal-loans-business-application-service
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

